### ISSUE TITLE
Trap URI::InvalidURIError as 404

### ISSUE THREAD

**Issue by hungrymedia** [seancdavis/sapwood-classic#242]
An URI::InvalidURIError occurred in #:

  bad URI(is not URI?): http://thornvalleysafety.com/documents/policies/towing company policy and safety manual

**Comment by seancdavis** [comment]
Forgot to close. Fixed with [ecf23b7](https://github.com/seancdavis/sapwood/commit/ecf23b7e9f8020cd55e0523718d60d3d50b129c2)

**Comment by seancdavis** [comment]
@hungrymedia: I'm trapping the error [here](https://github.com/seancdavis/sapwood/blob/master/app/controllers/viewer/pages_controller.rb#L5-17).

It is properly calling the `error_404` method and it is doing the 404 rendering and all that, but it is still triggering the exception notification message.

Any ideas on how we avoid the notification from being sent?

**Comment by hungrymedia** [comment]
@seancdavis  Are you sure it's not fixed? If I hit http://thornvalleysafety.com/Documents/LCW 10012 rollover 2.pdf in a browser, I see the 404 page and no error come through the Slack channel.

**Comment by seancdavis** [comment]
I see the same behavior, except I'm still seeing dozens of these errors coming into the Slack channel every hour.

**Comment by seancdavis** [comment]
@hungrymedia discovered the error was specific to secondary domains. It could be avoided simply by encoding the URL before redirecting to the primary domain. This is fixed with [this commit](https://github.com/seancdavis/sapwood/commit/da2557e6fbc5fa5f3f84449c1f8ba9c20ed082a3).

Thanks, @hungrymedia!
